name: CI BDD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Configurar Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 3️⃣ Construir el proyecto con Maven
      - name: Build with Maven
        run: mvn clean install

      # 4️⃣ Ejecutar pruebas BDD y generar reporte HTML
      - name: Run BDD Tests
        run: mvn test

      # 5️⃣ Subir reporte HTML como artifact
      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-report.html

